### ISSUE TITLE
Nix build fails

### ISSUE THREAD

**Issue by rasmus-kirk** [malteneuss/stack-with-nix-flake#1]
Hey, really like this, but if I try to just do `nix build`, it ends up complaining about the sandbox:

```
> nix build --option sandbox false
do you want to allow configuration setting 'sandbox' to be set to 'false' (y/N)? y
do you want to permanently mark this value as trusted (y/N)? y
error: derivation '/nix/store/2jiwpk71ix9hwypcrxk5x72lhaaak55n-myStack.drv' has '__noChroot' set, but that's not allowed when 'sandbox' is 'true'
```

**Comment by malteneuss** [comment]
I'm no longer using Stack as Cabal has become good enough in the mean time. For using it with Nix, i recommend using https://github.com/srid/haskell-template, which had the best out-of-the-box experience.
